import type { Metadata } from "next";
import { Barlow_Semi_Condensed, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { avantGarde, Butcherman, gambarino } from "./fonts/avantgarde";
import NavBar from "./components/Navbar";
import Footer from "./components/Footer";
import SmoothScrollProvider from "./components/SmoothScrollProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const barlow = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` `}>
      <body
        className={`${geistSans.variable} ${barlow.variable} ${geistMono.variable} ${avantGarde.variable} ${gambarino.variable} ${Butcherman.variable} antialiased`}
      >
        <SmoothScrollProvider />
        <NavBar />
        {/* <h1 className="font-gambarino text-3xl">Custom AvantGarde Heading</h1> */}

        {children}
        <Footer />
      </body>
    </html>
  );
}
